- name: "Nodejs setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yaml

- name: "App setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml


- name: "Reload service"
  ansible.builtin.import_role:
    name: common
    tasks_from: system-reload-setup.yaml
  