- name: "Repo copy and pasting"
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: "Install Rabbitmq"
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

- name: "Start and enable service"
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: "Rabbitmq user add"
  community.rabbitmq.rabbitmq_user:
    user: roboshop 
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
