- name: "Adding App user or Application user"
  ansible.builtin.user:
    name: roboshop
    comment: "roboshop system user" 
    shell: /sbin/nologin
    system: true
    home: /app

# Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
- name: "Remove app directory"
  ansible.builtin.file:
    path: /app
    state: absent

- name: "Creating app directory"
  ansible.builtin.file:
    path: /app
    state: directory

- name: "Deleting present {{ component }} code or {{ component }} file"
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: "Download the latest code"
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip

- name: "unzip the code "
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes

# new from cgpt ref
- name: Install npm dependencies
  community.general.npm:
    path: /app