---
- name: "App setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: "Nodejs setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yaml

- name: system setup
  ansible.builtin.import_role:
    name: common
    # tasks_from: system-setup.yaml
    tasks_from: service-setup.yaml


